version: "3.8"
services:
  task:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]
    # map user and group IDs to avoid permission issues with bind mounts
    user: "${UID}:${GID}"
    env_file:
      - .env.compose
      - .env
    volumes:
      - type: bind
        source: ../.. # Bind mount the entire repo
        target: /app
    ports:
      - "4096"
