#!/bin/bash
# Hyperbranch Run Script
# Generated by Hyperbranch CLI

set -e

# Use HB_CID_FILE if provided, else default to hb.cid
CID_FILE="${HB_CID_FILE:-hb.cid}"
RUN_DIR="${HB_RUN_DIR:-.}"

# Cleanup on exit
cleanup() {
    # Remove container and volumes
    if [ -n "$HB_PROJECT_NAME" ]; then
        docker compose -f "$RUN_DIR/docker-compose.yml" -p "$HB_PROJECT_NAME" down -v 2>/dev/null || true
    fi
}
trap cleanup SIGINT SIGTERM

echo "Starting Docker Container..."
echo "  Project: $HB_PROJECT_NAME"
echo "  Container: $HB_CONTAINER_NAME"

# Run container in detached mode via Docker Compose
# -d: Detached
# --name: Explicit container name
# --remove-orphans: Clean up old containers
# --service-ports: Map ports defined in compose
# task: The service name
# "$@": The command to run (passed from config.exec)

docker compose \
    -f "$RUN_DIR/docker-compose.yml" \
    -p "$HB_PROJECT_NAME" \
    run \
    -d \
    --name "$HB_CONTAINER_NAME" \
    --remove-orphans \
    --service-ports \
    task \
    "$@"

# Capture CID
# We use docker inspect because compose run returns immediately
HB_CID=$(docker inspect --format "{{.Id}}" "$HB_CONTAINER_NAME")

if [ -z "$HB_CID" ]; then
    echo "Error: Failed to capture Container ID"
    exit 1
fi

echo "$HB_CID" > "$CID_FILE"
echo "Container started with ID: $HB_CID"

